export const mockResultSendJsonRPCRequestWalletInfo = [
  {
    address: 'AU1QRRX6o2igWogY8qbBtqLYsNzYNHwvnpMC48Y6CLCv4cXe9gmK',
    thread: 6,
    final_balance: '500',
    final_roll_count: 0,
    final_datastore_keys: [],
    candidate_balance: '500',
    candidate_roll_count: 0,
    candidate_datastore_keys: [],
    deferred_credits: [],
    next_block_draws: [],
    next_endorsement_draws: [],
    created_blocks: [],
    created_operations: [],
    created_endorsements: [],
    cycle_infos: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    address: 'AU12eqpwwPeVxt2riAZZv2QMyFJ7qnZwBmATFRU3JKjkXvtupLHDS',
    thread: 27,
    final_balance: '0',
    final_roll_count: 0,
    final_datastore_keys: [],
    candidate_balance: '0',
    candidate_roll_count: 0,
    candidate_datastore_keys: [],
    deferred_credits: [],
    next_block_draws: [],
    next_endorsement_draws: [],
    created_blocks: [],
    created_operations: [],
    created_endorsements: [],
    cycle_infos: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
];
