// Copyright (c) 2023 MASSA LABS <info@massa.net>

// @generated by protoc-gen-es v1.2.0 with parameter "target=js+ts+dts"
// @generated from file api.proto (package massa.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { IndexedSlot, Slot } from "./slot_pb.js";
import { Block, FilledBlock, SignedBlock, SignedBlockHeader } from "./block_pb.js";
import { SignedOperation } from "./operation_pb.js";
import { SecureShare } from "./common_pb.js";
import { Status } from "./google/rpc/status_pb.js";

/**
 * Operation type enum
 *
 * @generated from enum massa.api.v1.OpType
 */
export const OpType = proto3.makeEnum(
  "massa.api.v1.OpType",
  [
    {no: 0, name: "OP_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "OP_TYPE_TRANSACTION", localName: "TRANSACTION"},
    {no: 2, name: "OP_TYPE_ROLL_BUY", localName: "ROLL_BUY"},
    {no: 3, name: "OP_TYPE_ROLL_SELL", localName: "ROLL_SELL"},
    {no: 4, name: "OP_TYPE_EXECUTE_SC", localName: "EXECUTE_SC"},
    {no: 5, name: "OP_TYPE_CALL_SC", localName: "CALL_SC"},
  ],
);

/**
 * GetBlocksBySlotsRequest holds request for GetBlocksBySlots
 *
 * @generated from message massa.api.v1.GetBlocksBySlotsRequest
 */
export const GetBlocksBySlotsRequest = proto3.makeMessageType(
  "massa.api.v1.GetBlocksBySlotsRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slots", kind: "message", T: Slot, repeated: true },
  ],
);

/**
 * GetBlocksBySlotsResponse holds response from GetBlocksBySlots
 *
 * @generated from message massa.api.v1.GetBlocksBySlotsResponse
 */
export const GetBlocksBySlotsResponse = proto3.makeMessageType(
  "massa.api.v1.GetBlocksBySlotsResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "blocks", kind: "message", T: Block, repeated: true },
  ],
);

/**
 * GetDatastoreEntriesRequest holds request from GetDatastoreEntries
 *
 * @generated from message massa.api.v1.GetDatastoreEntriesRequest
 */
export const GetDatastoreEntriesRequest = proto3.makeMessageType(
  "massa.api.v1.GetDatastoreEntriesRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "queries", kind: "message", T: DatastoreEntriesQuery, repeated: true },
  ],
);

/**
 * DatastoreEntries Query
 *
 * @generated from message massa.api.v1.DatastoreEntriesQuery
 */
export const DatastoreEntriesQuery = proto3.makeMessageType(
  "massa.api.v1.DatastoreEntriesQuery",
  () => [
    { no: 1, name: "filter", kind: "message", T: DatastoreEntryFilter },
  ],
);

/**
 * @generated from message massa.api.v1.DatastoreEntryFilter
 */
export const DatastoreEntryFilter = proto3.makeMessageType(
  "massa.api.v1.DatastoreEntryFilter",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * GetDatastoreEntriesResponse holds response from GetDatastoreEntries
 *
 * @generated from message massa.api.v1.GetDatastoreEntriesResponse
 */
export const GetDatastoreEntriesResponse = proto3.makeMessageType(
  "massa.api.v1.GetDatastoreEntriesResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "entries", kind: "message", T: DatastoreEntry, repeated: true },
  ],
);

/**
 * DatastoreEntry
 *
 * @generated from message massa.api.v1.DatastoreEntry
 */
export const DatastoreEntry = proto3.makeMessageType(
  "massa.api.v1.DatastoreEntry",
  () => [
    { no: 1, name: "final_value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "candidate_value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * GetNextBlockBestParentsRequest holds request for GetNextBlockBestParents
 *
 * @generated from message massa.api.v1.GetNextBlockBestParentsRequest
 */
export const GetNextBlockBestParentsRequest = proto3.makeMessageType(
  "massa.api.v1.GetNextBlockBestParentsRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GetNextBlockBestParentsResponse holds response from GetNextBlockBestParents
 *
 * @generated from message massa.api.v1.GetNextBlockBestParentsResponse
 */
export const GetNextBlockBestParentsResponse = proto3.makeMessageType(
  "massa.api.v1.GetNextBlockBestParentsResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "parents", kind: "message", T: BlockParent, repeated: true },
  ],
);

/**
 * Block parent tuple
 *
 * @generated from message massa.api.v1.BlockParent
 */
export const BlockParent = proto3.makeMessageType(
  "massa.api.v1.BlockParent",
  () => [
    { no: 1, name: "block_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "period", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
  ],
);

/**
 * GetSelectorDrawsRequest holds request from GetSelectorDraws
 *
 * @generated from message massa.api.v1.GetSelectorDrawsRequest
 */
export const GetSelectorDrawsRequest = proto3.makeMessageType(
  "massa.api.v1.GetSelectorDrawsRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "queries", kind: "message", T: SelectorDrawsQuery, repeated: true },
  ],
);

/**
 * SelectorDraws Query
 *
 * @generated from message massa.api.v1.SelectorDrawsQuery
 */
export const SelectorDrawsQuery = proto3.makeMessageType(
  "massa.api.v1.SelectorDrawsQuery",
  () => [
    { no: 1, name: "filter", kind: "message", T: SelectorDrawsFilter },
  ],
);

/**
 * SelectorDraws Filter
 *
 * @generated from message massa.api.v1.SelectorDrawsFilter
 */
export const SelectorDrawsFilter = proto3.makeMessageType(
  "massa.api.v1.SelectorDrawsFilter",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GetSelectorDrawsResponse holds response from GetSelectorDraws
 *
 * @generated from message massa.api.v1.GetSelectorDrawsResponse
 */
export const GetSelectorDrawsResponse = proto3.makeMessageType(
  "massa.api.v1.GetSelectorDrawsResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "selector_draws", kind: "message", T: SelectorDraws, repeated: true },
  ],
);

/**
 * Selector draws
 *
 * @generated from message massa.api.v1.SelectorDraws
 */
export const SelectorDraws = proto3.makeMessageType(
  "massa.api.v1.SelectorDraws",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "next_block_draws", kind: "message", T: Slot, repeated: true },
    { no: 3, name: "next_endorsement_draws", kind: "message", T: IndexedSlot, repeated: true },
  ],
);

/**
 * GetTransactionsThroughputRequest holds request for GetTransactionsThroughput
 *
 * @generated from message massa.api.v1.GetTransactionsThroughputRequest
 */
export const GetTransactionsThroughputRequest = proto3.makeMessageType(
  "massa.api.v1.GetTransactionsThroughputRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GetTransactionsThroughputResponse holds response from GetTransactionsThroughput
 *
 * @generated from message massa.api.v1.GetTransactionsThroughputResponse
 */
export const GetTransactionsThroughputResponse = proto3.makeMessageType(
  "massa.api.v1.GetTransactionsThroughputResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "throughput", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
  ],
);

/**
 * GetVersionRequest holds request from GetVersion
 *
 * @generated from message massa.api.v1.GetVersionRequest
 */
export const GetVersionRequest = proto3.makeMessageType(
  "massa.api.v1.GetVersionRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GetVersionResponse holds response from GetVersion
 *
 * @generated from message massa.api.v1.GetVersionResponse
 */
export const GetVersionResponse = proto3.makeMessageType(
  "massa.api.v1.GetVersionResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * NewBlocksRequest holds request for NewBlocks
 *
 * @generated from message massa.api.v1.NewBlocksRequest
 */
export const NewBlocksRequest = proto3.makeMessageType(
  "massa.api.v1.NewBlocksRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * NewBlocksResponse holds response from NewBlocks
 *
 * @generated from message massa.api.v1.NewBlocksResponse
 */
export const NewBlocksResponse = proto3.makeMessageType(
  "massa.api.v1.NewBlocksResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "block", kind: "message", T: SignedBlock },
  ],
);

/**
 * NewBlocksHeadersRequest holds request for NewBlocksHeaders
 *
 * @generated from message massa.api.v1.NewBlocksHeadersRequest
 */
export const NewBlocksHeadersRequest = proto3.makeMessageType(
  "massa.api.v1.NewBlocksHeadersRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * NewBlocksHeadersResponse holds response from NewBlocksHeaders
 *
 * @generated from message massa.api.v1.NewBlocksHeadersResponse
 */
export const NewBlocksHeadersResponse = proto3.makeMessageType(
  "massa.api.v1.NewBlocksHeadersResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "block_header", kind: "message", T: SignedBlockHeader },
  ],
);

/**
 * NewFilledBlocksRequest holds request for NewFilledBlocks
 *
 * @generated from message massa.api.v1.NewFilledBlocksRequest
 */
export const NewFilledBlocksRequest = proto3.makeMessageType(
  "massa.api.v1.NewFilledBlocksRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * NewFilledBlocksResponse holds response from NewFilledBlocks
 *
 * @generated from message massa.api.v1.NewFilledBlocksResponse
 */
export const NewFilledBlocksResponse = proto3.makeMessageType(
  "massa.api.v1.NewFilledBlocksResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "filled_block", kind: "message", T: FilledBlock },
  ],
);

/**
 * NewOperationsRequest holds request for NewOperations
 *
 * @generated from message massa.api.v1.NewOperationsRequest
 */
export const NewOperationsRequest = proto3.makeMessageType(
  "massa.api.v1.NewOperationsRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "query", kind: "message", T: NewOperationsQuery },
  ],
);

/**
 * NewOperations Query
 *
 * @generated from message massa.api.v1.NewOperationsQuery
 */
export const NewOperationsQuery = proto3.makeMessageType(
  "massa.api.v1.NewOperationsQuery",
  () => [
    { no: 1, name: "filter", kind: "message", T: NewOperationsFilter },
  ],
);

/**
 * NewOperations Filter
 *
 * @generated from message massa.api.v1.NewOperationsFilter
 */
export const NewOperationsFilter = proto3.makeMessageType(
  "massa.api.v1.NewOperationsFilter",
  () => [
    { no: 1, name: "types", kind: "enum", T: proto3.getEnumType(OpType), repeated: true },
  ],
);

/**
 * NewOperationsResponse holds response from NewOperations
 *
 * @generated from message massa.api.v1.NewOperationsResponse
 */
export const NewOperationsResponse = proto3.makeMessageType(
  "massa.api.v1.NewOperationsResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "operation", kind: "message", T: SignedOperation },
  ],
);

/**
 * SendBlocksRequest holds parameters to SendBlocks
 *
 * @generated from message massa.api.v1.SendBlocksRequest
 */
export const SendBlocksRequest = proto3.makeMessageType(
  "massa.api.v1.SendBlocksRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "block", kind: "message", T: SecureShare },
  ],
);

/**
 * SendBlocksResponse holds response from SendBlocks
 *
 * @generated from message massa.api.v1.SendBlocksResponse
 */
export const SendBlocksResponse = proto3.makeMessageType(
  "massa.api.v1.SendBlocksResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "result", kind: "message", T: BlockResult, oneof: "message" },
    { no: 3, name: "error", kind: "message", T: Status, oneof: "message" },
  ],
);

/**
 * Holds Block response
 *
 * @generated from message massa.api.v1.BlockResult
 */
export const BlockResult = proto3.makeMessageType(
  "massa.api.v1.BlockResult",
  () => [
    { no: 1, name: "block_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * SendEndorsementsRequest holds parameters to SendEndorsements
 *
 * @generated from message massa.api.v1.SendEndorsementsRequest
 */
export const SendEndorsementsRequest = proto3.makeMessageType(
  "massa.api.v1.SendEndorsementsRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "endorsements", kind: "message", T: SecureShare, repeated: true },
  ],
);

/**
 * SendEndorsementsResponse holds response from SendEndorsements
 *
 * @generated from message massa.api.v1.SendEndorsementsResponse
 */
export const SendEndorsementsResponse = proto3.makeMessageType(
  "massa.api.v1.SendEndorsementsResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "result", kind: "message", T: EndorsementResult, oneof: "message" },
    { no: 3, name: "error", kind: "message", T: Status, oneof: "message" },
  ],
);

/**
 * Holds Endorsement response
 *
 * @generated from message massa.api.v1.EndorsementResult
 */
export const EndorsementResult = proto3.makeMessageType(
  "massa.api.v1.EndorsementResult",
  () => [
    { no: 1, name: "endorsements_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * SendOperationsRequest holds parameters to SendOperations
 *
 * @generated from message massa.api.v1.SendOperationsRequest
 */
export const SendOperationsRequest = proto3.makeMessageType(
  "massa.api.v1.SendOperationsRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "operations", kind: "message", T: SecureShare, repeated: true },
  ],
);

/**
 * SendOperationsResponse holds response from SendOperations
 *
 * @generated from message massa.api.v1.SendOperationsResponse
 */
export const SendOperationsResponse = proto3.makeMessageType(
  "massa.api.v1.SendOperationsResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "result", kind: "message", T: OperationResult, oneof: "message" },
    { no: 3, name: "error", kind: "message", T: Status, oneof: "message" },
  ],
);

/**
 * Holds Operation response
 *
 * @generated from message massa.api.v1.OperationResult
 */
export const OperationResult = proto3.makeMessageType(
  "massa.api.v1.OperationResult",
  () => [
    { no: 1, name: "operations_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * TransactionsThroughputRequest holds request for TransactionsThroughput
 *
 * @generated from message massa.api.v1.TransactionsThroughputRequest
 */
export const TransactionsThroughputRequest = proto3.makeMessageType(
  "massa.api.v1.TransactionsThroughputRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interval", kind: "scalar", T: 6 /* ScalarType.FIXED64 */, opt: true },
  ],
);

/**
 * TransactionsThroughputResponse holds response from TransactionsThroughput
 *
 * @generated from message massa.api.v1.TransactionsThroughputResponse
 */
export const TransactionsThroughputResponse = proto3.makeMessageType(
  "massa.api.v1.TransactionsThroughputResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "throughput", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
  ],
);

