// Copyright (c) 2023 MASSA LABS <info@massa.net>

// @generated by protoc-gen-es v1.2.0 with parameter "target=js+ts+dts"
// @generated from file block.proto (package massa.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Slot } from "./slot_pb.js";
import { SignedEndorsement } from "./endorsement_pb.js";
import { SignedOperation } from "./operation_pb.js";

/**
 * Block
 *
 * @generated from message massa.api.v1.Block
 */
export const Block = proto3.makeMessageType(
  "massa.api.v1.Block",
  () => [
    { no: 1, name: "header", kind: "message", T: SignedBlockHeader },
    { no: 2, name: "operations", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * Filled block
 *
 * @generated from message massa.api.v1.FilledBlock
 */
export const FilledBlock = proto3.makeMessageType(
  "massa.api.v1.FilledBlock",
  () => [
    { no: 1, name: "header", kind: "message", T: SignedBlockHeader },
    { no: 2, name: "operations", kind: "message", T: FilledOperationTuple, repeated: true },
  ],
);

/**
 * Block header
 *
 * @generated from message massa.api.v1.BlockHeader
 */
export const BlockHeader = proto3.makeMessageType(
  "massa.api.v1.BlockHeader",
  () => [
    { no: 1, name: "slot", kind: "message", T: Slot },
    { no: 2, name: "parents", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "operation_merkle_root", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "endorsements", kind: "message", T: SignedEndorsement, repeated: true },
  ],
);

/**
 * Filled Operation Tuple
 *
 * @generated from message massa.api.v1.FilledOperationTuple
 */
export const FilledOperationTuple = proto3.makeMessageType(
  "massa.api.v1.FilledOperationTuple",
  () => [
    { no: 1, name: "operation_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "operation", kind: "message", T: SignedOperation },
  ],
);

/**
 * Signed block
 *
 * @generated from message massa.api.v1.SignedBlock
 */
export const SignedBlock = proto3.makeMessageType(
  "massa.api.v1.SignedBlock",
  () => [
    { no: 1, name: "content", kind: "message", T: Block },
    { no: 2, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content_creator_pub_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "content_creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Signed block header
 *
 * @generated from message massa.api.v1.SignedBlockHeader
 */
export const SignedBlockHeader = proto3.makeMessageType(
  "massa.api.v1.SignedBlockHeader",
  () => [
    { no: 1, name: "content", kind: "message", T: BlockHeader },
    { no: 2, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content_creator_pub_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "content_creator_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

