// source: operation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.massa.api.v1.CallSC');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.massa.api.v1.CallSC = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.massa.api.v1.CallSC, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.massa.api.v1.CallSC.displayName = 'proto.massa.api.v1.CallSC';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.massa.api.v1.CallSC.prototype.toObject = function(opt_includeInstance) {
  return proto.massa.api.v1.CallSC.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.massa.api.v1.CallSC} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.massa.api.v1.CallSC.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetAddr: jspb.Message.getFieldWithDefault(msg, 1, ""),
    targetFunc: jspb.Message.getFieldWithDefault(msg, 2, ""),
    param: msg.getParam_asB64(),
    maxGas: jspb.Message.getFieldWithDefault(msg, 4, 0),
    coins: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.massa.api.v1.CallSC}
 */
proto.massa.api.v1.CallSC.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.massa.api.v1.CallSC;
  return proto.massa.api.v1.CallSC.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.massa.api.v1.CallSC} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.massa.api.v1.CallSC}
 */
proto.massa.api.v1.CallSC.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetAddr(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetFunc(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setParam(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setMaxGas(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setCoins(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.massa.api.v1.CallSC.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.massa.api.v1.CallSC.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.massa.api.v1.CallSC} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.massa.api.v1.CallSC.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetAddr();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTargetFunc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getParam_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getMaxGas();
  if (f !== 0) {
    writer.writeFixed64(
      4,
      f
    );
  }
  f = message.getCoins();
  if (f !== 0) {
    writer.writeFixed64(
      5,
      f
    );
  }
};


/**
 * optional string target_addr = 1;
 * @return {string}
 */
proto.massa.api.v1.CallSC.prototype.getTargetAddr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.massa.api.v1.CallSC} returns this
 */
proto.massa.api.v1.CallSC.prototype.setTargetAddr = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string target_func = 2;
 * @return {string}
 */
proto.massa.api.v1.CallSC.prototype.getTargetFunc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.massa.api.v1.CallSC} returns this
 */
proto.massa.api.v1.CallSC.prototype.setTargetFunc = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes param = 3;
 * @return {string}
 */
proto.massa.api.v1.CallSC.prototype.getParam = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes param = 3;
 * This is a type-conversion wrapper around `getParam()`
 * @return {string}
 */
proto.massa.api.v1.CallSC.prototype.getParam_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getParam()));
};


/**
 * optional bytes param = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getParam()`
 * @return {!Uint8Array}
 */
proto.massa.api.v1.CallSC.prototype.getParam_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getParam()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.massa.api.v1.CallSC} returns this
 */
proto.massa.api.v1.CallSC.prototype.setParam = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional fixed64 max_gas = 4;
 * @return {number}
 */
proto.massa.api.v1.CallSC.prototype.getMaxGas = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.massa.api.v1.CallSC} returns this
 */
proto.massa.api.v1.CallSC.prototype.setMaxGas = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional fixed64 coins = 5;
 * @return {number}
 */
proto.massa.api.v1.CallSC.prototype.getCoins = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.massa.api.v1.CallSC} returns this
 */
proto.massa.api.v1.CallSC.prototype.setCoins = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


