// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.massa.api.v1.SelectorDraws');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.massa.api.v1.IndexedSlot');
goog.require('proto.massa.api.v1.Slot');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.massa.api.v1.SelectorDraws = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.massa.api.v1.SelectorDraws.repeatedFields_, null);
};
goog.inherits(proto.massa.api.v1.SelectorDraws, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.massa.api.v1.SelectorDraws.displayName = 'proto.massa.api.v1.SelectorDraws';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.massa.api.v1.SelectorDraws.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.massa.api.v1.SelectorDraws.prototype.toObject = function(opt_includeInstance) {
  return proto.massa.api.v1.SelectorDraws.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.massa.api.v1.SelectorDraws} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.massa.api.v1.SelectorDraws.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nextBlockDrawsList: jspb.Message.toObjectList(msg.getNextBlockDrawsList(),
    proto.massa.api.v1.Slot.toObject, includeInstance),
    nextEndorsementDrawsList: jspb.Message.toObjectList(msg.getNextEndorsementDrawsList(),
    proto.massa.api.v1.IndexedSlot.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.massa.api.v1.SelectorDraws}
 */
proto.massa.api.v1.SelectorDraws.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.massa.api.v1.SelectorDraws;
  return proto.massa.api.v1.SelectorDraws.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.massa.api.v1.SelectorDraws} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.massa.api.v1.SelectorDraws}
 */
proto.massa.api.v1.SelectorDraws.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = new proto.massa.api.v1.Slot;
      reader.readMessage(value,proto.massa.api.v1.Slot.deserializeBinaryFromReader);
      msg.addNextBlockDraws(value);
      break;
    case 3:
      var value = new proto.massa.api.v1.IndexedSlot;
      reader.readMessage(value,proto.massa.api.v1.IndexedSlot.deserializeBinaryFromReader);
      msg.addNextEndorsementDraws(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.massa.api.v1.SelectorDraws.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.massa.api.v1.SelectorDraws.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.massa.api.v1.SelectorDraws} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.massa.api.v1.SelectorDraws.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNextBlockDrawsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.massa.api.v1.Slot.serializeBinaryToWriter
    );
  }
  f = message.getNextEndorsementDrawsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.massa.api.v1.IndexedSlot.serializeBinaryToWriter
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.massa.api.v1.SelectorDraws.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.massa.api.v1.SelectorDraws} returns this
 */
proto.massa.api.v1.SelectorDraws.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Slot next_block_draws = 2;
 * @return {!Array<!proto.massa.api.v1.Slot>}
 */
proto.massa.api.v1.SelectorDraws.prototype.getNextBlockDrawsList = function() {
  return /** @type{!Array<!proto.massa.api.v1.Slot>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.massa.api.v1.Slot, 2));
};


/**
 * @param {!Array<!proto.massa.api.v1.Slot>} value
 * @return {!proto.massa.api.v1.SelectorDraws} returns this
*/
proto.massa.api.v1.SelectorDraws.prototype.setNextBlockDrawsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.massa.api.v1.Slot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.massa.api.v1.Slot}
 */
proto.massa.api.v1.SelectorDraws.prototype.addNextBlockDraws = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.massa.api.v1.Slot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.massa.api.v1.SelectorDraws} returns this
 */
proto.massa.api.v1.SelectorDraws.prototype.clearNextBlockDrawsList = function() {
  return this.setNextBlockDrawsList([]);
};


/**
 * repeated IndexedSlot next_endorsement_draws = 3;
 * @return {!Array<!proto.massa.api.v1.IndexedSlot>}
 */
proto.massa.api.v1.SelectorDraws.prototype.getNextEndorsementDrawsList = function() {
  return /** @type{!Array<!proto.massa.api.v1.IndexedSlot>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.massa.api.v1.IndexedSlot, 3));
};


/**
 * @param {!Array<!proto.massa.api.v1.IndexedSlot>} value
 * @return {!proto.massa.api.v1.SelectorDraws} returns this
*/
proto.massa.api.v1.SelectorDraws.prototype.setNextEndorsementDrawsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.massa.api.v1.IndexedSlot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.massa.api.v1.IndexedSlot}
 */
proto.massa.api.v1.SelectorDraws.prototype.addNextEndorsementDraws = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.massa.api.v1.IndexedSlot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.massa.api.v1.SelectorDraws} returns this
 */
proto.massa.api.v1.SelectorDraws.prototype.clearNextEndorsementDrawsList = function() {
  return this.setNextEndorsementDrawsList([]);
};


