// source: api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.massa.api.v1.SendBlocksResponse');
goog.provide('proto.massa.api.v1.SendBlocksResponse.MessageCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.google.rpc.Status');
goog.require('proto.massa.api.v1.BlockResult');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.massa.api.v1.SendBlocksResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.massa.api.v1.SendBlocksResponse.oneofGroups_);
};
goog.inherits(proto.massa.api.v1.SendBlocksResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.massa.api.v1.SendBlocksResponse.displayName = 'proto.massa.api.v1.SendBlocksResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.massa.api.v1.SendBlocksResponse.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.massa.api.v1.SendBlocksResponse.MessageCase = {
  MESSAGE_NOT_SET: 0,
  RESULT: 2,
  ERROR: 3
};

/**
 * @return {proto.massa.api.v1.SendBlocksResponse.MessageCase}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.getMessageCase = function() {
  return /** @type {proto.massa.api.v1.SendBlocksResponse.MessageCase} */(jspb.Message.computeOneofCase(this, proto.massa.api.v1.SendBlocksResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.massa.api.v1.SendBlocksResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.massa.api.v1.SendBlocksResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.massa.api.v1.SendBlocksResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    result: (f = msg.getResult()) && proto.massa.api.v1.BlockResult.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.google.rpc.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.massa.api.v1.SendBlocksResponse}
 */
proto.massa.api.v1.SendBlocksResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.massa.api.v1.SendBlocksResponse;
  return proto.massa.api.v1.SendBlocksResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.massa.api.v1.SendBlocksResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.massa.api.v1.SendBlocksResponse}
 */
proto.massa.api.v1.SendBlocksResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.massa.api.v1.BlockResult;
      reader.readMessage(value,proto.massa.api.v1.BlockResult.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    case 3:
      var value = new proto.google.rpc.Status;
      reader.readMessage(value,proto.google.rpc.Status.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.massa.api.v1.SendBlocksResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.massa.api.v1.SendBlocksResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.massa.api.v1.SendBlocksResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.massa.api.v1.BlockResult.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.rpc.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.massa.api.v1.SendBlocksResponse} returns this
 */
proto.massa.api.v1.SendBlocksResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional BlockResult result = 2;
 * @return {?proto.massa.api.v1.BlockResult}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.getResult = function() {
  return /** @type{?proto.massa.api.v1.BlockResult} */ (
    jspb.Message.getWrapperField(this, proto.massa.api.v1.BlockResult, 2));
};


/**
 * @param {?proto.massa.api.v1.BlockResult|undefined} value
 * @return {!proto.massa.api.v1.SendBlocksResponse} returns this
*/
proto.massa.api.v1.SendBlocksResponse.prototype.setResult = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.massa.api.v1.SendBlocksResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.massa.api.v1.SendBlocksResponse} returns this
 */
proto.massa.api.v1.SendBlocksResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.rpc.Status error = 3;
 * @return {?proto.google.rpc.Status}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.getError = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, proto.google.rpc.Status, 3));
};


/**
 * @param {?proto.google.rpc.Status|undefined} value
 * @return {!proto.massa.api.v1.SendBlocksResponse} returns this
*/
proto.massa.api.v1.SendBlocksResponse.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.massa.api.v1.SendBlocksResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.massa.api.v1.SendBlocksResponse} returns this
 */
proto.massa.api.v1.SendBlocksResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.massa.api.v1.SendBlocksResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 3) != null;
};


