// Copyright (c) 2023 MASSA LABS <info@massa.net>

// @generated by protoc-gen-es v1.2.0 with parameter "target=js+ts+dts"
// @generated from file slot.proto (package massa.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * When an address is drawn to create an endorsement it is selected for a specific index
 *
 * @generated from message massa.api.v1.IndexedSlot
 */
export class IndexedSlot extends Message<IndexedSlot> {
  /**
   * Slot
   *
   * @generated from field: massa.api.v1.Slot slot = 1;
   */
  slot?: Slot;

  /**
   * Endorsement index in the slot
   *
   * @generated from field: fixed64 index = 2;
   */
  index = protoInt64.zero;

  constructor(data?: PartialMessage<IndexedSlot>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "massa.api.v1.IndexedSlot";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "slot", kind: "message", T: Slot },
    { no: 2, name: "index", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IndexedSlot {
    return new IndexedSlot().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IndexedSlot {
    return new IndexedSlot().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IndexedSlot {
    return new IndexedSlot().fromJsonString(jsonString, options);
  }

  static equals(a: IndexedSlot | PlainMessage<IndexedSlot> | undefined, b: IndexedSlot | PlainMessage<IndexedSlot> | undefined): boolean {
    return proto3.util.equals(IndexedSlot, a, b);
  }
}

/**
 * A point in time where a block is expected
 *
 * @generated from message massa.api.v1.Slot
 */
export class Slot extends Message<Slot> {
  /**
   * Period
   *
   * @generated from field: fixed64 period = 1;
   */
  period = protoInt64.zero;

  /**
   * Thread
   *
   * @generated from field: fixed32 thread = 2;
   */
  thread = 0;

  constructor(data?: PartialMessage<Slot>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "massa.api.v1.Slot";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "period", kind: "scalar", T: 6 /* ScalarType.FIXED64 */ },
    { no: 2, name: "thread", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Slot {
    return new Slot().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Slot {
    return new Slot().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Slot {
    return new Slot().fromJsonString(jsonString, options);
  }

  static equals(a: Slot | PlainMessage<Slot> | undefined, b: Slot | PlainMessage<Slot> | undefined): boolean {
    return proto3.util.equals(Slot, a, b);
  }
}

