import { ISlot } from "./ISlot";

export interface IEvent {
    id?: string; // event id
    data: string; // Arbitrary json string generated by the smart contract
    context: {
        slot: ISlot,
		block: null | string // block id,
		read_only: boolean // wether the event was generated during read only call
		call_stack: [string], // Addresses (most recent at the end)
        index_in_slot: number,
        origin_operation_id: null | string, // operation id
        is_final: boolean, // Whether the event is final
        is_error: boolean, // Whether the event was generated in a failed executed or not
    };
}
