import { IEvent } from "./IEvent";
import { ISlot } from "./ISlot";

export interface IExecuteReadOnlyResponse {
    /// The slot at which the read-only execution occured.
	executed_at: ISlot;
    /// The result fo the read-only execution.
	result: string | null;
    /// The output events generated by the read-only execution.
	output_events: Map<string, IEvent>;
}