name: (workspace) Deploy documentation

on:
  push:
    tags:
      - v*

jobs:
  deploy-typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate doc
        run: |
          npm ci
          npm run doc
          mv docs/documentation/html massa-web3
      - name: Deploy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MASSANET_HOST }}
          username: ${{ secrets.MASSANET_USERNAME }}
          key: ${{ secrets.MASSANET_SSHKEY }}
          source: "./massa-web3"
          target: "/var/www/type-doc"
