name: Npm nightly publish

on:
  push:
    branches: [main, buildnet]

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    secrets:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  publish-npm-dev:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          registry-url: https://registry.npmjs.org
      - run: ./scripts/publish-dev.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
