name: Check Formatting and Run unit tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: |
          npm ci
          npm run build
      - run: npm run fmt:check

      - name: unit test
        run: npm test

      - name: unit test browser
        run: npm run test:browser
